---
- name: Install runtime
  include_tasks: "containerd.yaml"

- name: Clear Containerd Components
  include_tasks: delete-containerd-components.yaml
  when: agorakube_base_components.container.engine == "containerd"
  tags: ['never', 'uninstall']
