---
- name: Include label hosts
  include_tasks: label-hosts.yaml

- name: Include Tasks Calico
  include_tasks: calico.yaml
  when: agorakube_network.cni_plugin == 'calico'

- name: Wait for nodes to be ready after CNI-Plugin deployment
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get node {{ item }}
  changed_when: false
  register: node_deployment
  until: node_deployment.stdout.find("Ready") != -1
  retries: 300
  delay: 10
  run_once: true
  with_items:
    - "{{ groups['masters'] }}"
    - "{{ groups['workers'] }}"

- name: Deploy CoreDNS to K8S
  include_tasks: coredns.yaml

- name: Install MetalLB Layer2
  include_tasks: metallb_l2.yaml
  when: agorakube_network.external_loadbalancing.enabled | bool == True

- name: Install Metrics-Server
  include_tasks: metrics-server.yaml
  when: agorakube_features.metrics_server.enabled | bool == True

- name: Install ingress (nginx)
  include_tasks: nginx.yaml
  when: agorakube_features.ingress.controller == 'nginx'

- name: Install K8S Default Dashboard
  include_tasks: default_dashboard.yaml
  when: agorakube_features.dashboard.enabled | bool == True